#!/bin/bash

echo What is the name of  your asm file add asm extension?

read path



filename=$(basename -- $path)
filename="${filename%.*}"

nasm -f elf $path

ld -m elf_i386 -s -o $filename $filename.o


